server:
  port: 8080
spring:
  application:
    name:web
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgres.Driver